version: "3.9"
services:
  postgres:
    image: postgres:bullseye
    container_name: authorization_pg
    env_file: ./.env
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/post
  redis:
    image: redis:bullseye
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
